name: Continuous Integration

on:
  pull_request:
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Installing rustfmt
        run: rustup component add rustfmt
      - name: Running rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
    
  lint:
    needs: [codestyle]
    runs-on: ubuntu-latest
    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Installing clippy
        run: rustup component add clippy
      - name: Linting project
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

  check:
    needs: [lint]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
          - os: ubuntu-latest
    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true 
      - name: Checking out sources
        uses: actions/checkout@v1
      - name: Checking Rust code
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --locked --no-default-features --features ${{ matrix.features }}
